# Generated by Django 3.0.5 on 2020-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.CharField(max_length=1500)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('claps', models.IntegerField(default=0)),
            ],
        ),
    ]
