# Generated by Django 3.0.5 on 2020-04-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogposts',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.RenameField(
            model_name='blogposts',
            old_name='id',
            new_name='post_id',
        ),
    ]
