# Generated by Django 3.0.6 on 2020-05-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200430_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_content',
            field=models.TextField(),
        ),
    ]
