# Generated by Django 3.0.6 on 2020-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200516_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_content',
            field=models.CharField(max_length=1500),
        ),
    ]
