# Generated by Django 3.0.6 on 2020-05-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogposts_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='author_id',
        ),
    ]
