# Generated by Django 3.0.6 on 2020-05-16 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogposts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
