# Generated by Django 3.0.6 on 2020-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200516_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
