# Generated by Django 3.0.6 on 2020-06-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
        ('blog', '0010_auto_20200528_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
