# Generated by Django 3.0.6 on 2020-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_characters_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Characters',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
